- hosts: elacpitan_head
  order: sorted
  vars:
    users:
      - name: "mlen2"
        uid: 623
      - name: "aparopkari"
        groups: "wheel"
        uid: 1005
  tasks:
  - name: ensure a list of packages are not installed
    yum:
      name: "{{ packages }}"
      state: absent
    vars:
      packages:
      - yelp
      - yelp-libs
      - yelp-xls
  - name: ensure epel is installed
    yum:
      state: latest
      name: 'epel-release'
  - name: ensure all packages are up-to-date
    yum:
      state: latest
      name: '*'
  - name: ensure necessary software are installed
    yum:
      name: ipmitool,dnsmasq,vsftpd,nfs-utils,ansible,mariadb-server,mariadb-devel,rng-tools,fail2ban,rpm-build 
      state: latest
  - name: ensure convenient software are installed
    yum:
      name: htop,wget,tree,vim,dnf
      state: latest
  - name: Make sure vsftpd is off ... not PXE booting for now.
    systemd:
      name: vsftpd
      state: stopped
  - name: Ensure fstab can mount coraid, and is mounted
    mount:
        path: /home
        src: 192.168.0.70:/mnt/md0
        fstype: nfs
        opts: defaults,rw,noatime
        state: mounted
        boot: yes
  - name: Copy file with owner and permissions
    copy:
      src: etc/fail2ban/jail.local
      dest: /etc/fail2ban/jail.local
      owner: root
      group: root
      mode: '0600'
  - name: Make sure a service is running
    systemd:
      state: restarted
      name: fail2ban
  - name: setup slurm
    yum:
      state: present
      name: munge, slurm
  - name: Create the slurm conf directory
    file:
      path: /etc/slurm
      owner: root
      group: root
      mode: o=rx
      state: directory
  - name: copy slurm conf
    copy:
      src: etc/slurm/slurm.conf
      dest: /etc/slurm/slurm.conf
      owner: root
      group: root
      mode: o=rx
  - name: Create a JupyterHub user to host the JupyterHub environment
    user:
      update_password: on_create
      name: jupyterhub
      comment: Jupyter Hub User
      uid: 800
  - name: Add Matthias account as a sudoers.
    user:
      update_password: on_create
      name: mbussonnier
      comment: Matthias Bussonnier
      uid: 1001
      password: $6$c6QlFGDbfQoQ/WPm$WmBLKGSZ4poAwJQQqyyNMTO0tiTaFzprgLQouPUq2yVe6V27XItZLnvv9qd1FJ7/EHm4cPCqzwyP3qLothao90
      groups: wheel
  - openssh_keypair:
      path: /home/mbussonnier/.ssh/id_rsa
      owner: mbussonnier
      group: mbussonnier
      size: 2048
  - name: Create users accounts.
    user:
      update_password: on_create
      name: "{{item['name']}}"
      comment: "The comments"
      uid: "{{item['uid']}}"
      groups: "{{item['groups']}}"
    loop: "{{users}}"
