- hosts: elcapitan_compute
  order: sorted
  strategy: free
  tasks:
  - name: copy slurm conf
    copy:
      src: etc/slurm/slurm.conf
      dest: /etc/slurm/slurm.conf
      owner: root
      group: root
  - name: Make sure munge is started for slurm authentication
    systemd:
      state: started
      enabled: yes
      name: munge
  - name: Make sure slurmd is started for job submission
    systemd:
      state: restarted
      enabled : yes
      name: slurmd
  - name: Add Matthias account as a sudoers.
    user:
      update_password: on_create
      name: mbussonnier
      comment: Matthias Bussonnier
      uid: 1001
      password: $6$c6QlFGDbfQoQ/WPm$WmBLKGSZ4poAwJQQqyyNMTO0tiTaFzprgLQouPUq2yVe6V27XItZLnvv9qd1FJ7/EHm4cPCqzwyP3qLothao90
      groups: wheel
  - name: Set authorized key for user ubuntu copying it from current user
    authorized_key:
      user: mbussonnier
      state: present
      key: "{{ lookup('file', '/home/mbussonnier/.ssh/id_rsa.pub') }}"
